version: 1

platforms:
  - name: My_Nexus_5
    avd:
      package: "system-images;android-27;google_apis_playstore;x86"
      device: Nexus 5
      force: True
    emulator:

  - name: My_Nexus_One
    avd:
      package: "system-images;android-27;google_apis_playstore;x86"
      device: Nexus One
      force: True
    emulator:

  - name: My_Nexus_9
    avd:
      package: "system-images;android-27;google_apis_playstore;x86"
      device: Nexus 9
      force: True
    emulator:
